import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import CartProvider from "@/context/CartContext";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export const myMenu = [
  {
    title:"Home",
    url:'/'
  },
  {
    title:"Shop",
    url:'/shop'
  },
  {
    title:"About us",
    url:'/about'
  },
  {
    title:"Contact",
    url:'/'
  },
]



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <CartProvider>
        <Navbar logo="https://klbtheme.com/bevesi/wp-content/uploads/2024/03/logo-dark.png" menu={myMenu} />
        {children}
        <Footer/>
        </CartProvider>
      </body>
    </html>
  );
}
