import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import CartProvider from "@/context/CartContext";
import Providers from "@/context/Providers";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export const myMenu = [
  {
    title: "Home",
    url: '/'
  },
  {
    title: "Shop",
    url: '/shop'
  },
  {
    title: "About us",
    url: '/about'
  },
  {
    title: "Contact",
    url: '/'
  },
]



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Providers>
          <CartProvider>
            <Navbar logo="https://klbtheme.com/bevesi/wp-content/uploads/2024/03/logo-dark.png" menu={myMenu} />
            {children}
            <Footer />
          </CartProvider>
        </Providers>
      </body>
    </html>
  );
}
